import { Item } from "../utils/itineraryUtils";

export const data: Item[][] = [
  [
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 1,
      name: "Govind Dev Ji Temple",
      significance:
        "A historic temple dedicated to Lord Krishna with remarkable architecture.",
      state: "Rajasthan",
      type: "Temple",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 2,
      name: "Birla Mandir",
      significance:
        "Modern Hindu temple surrounded by lush greenery, dedicated to Lord Vishnu and Goddess Lakshmi.",
      state: "Rajasthan",
      type: "Temple",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 3,
      name: "Moti Dungri Ganesh Temple",
      significance:
        "A famous temple known for its intricate architecture and spiritual significance.",
      state: "Rajasthan",
      type: "Temple",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 12,
      name: "Chokhi Dhani",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 15,
      name: "The Rajput Room",
      banner: "/placeholder.jpg",
    },
  ],
  [
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 4,
      name: "Amber Fort",
      significance:
        "A grand fort showcasing the majestic blend of Hindu and Mughal architecture.",
      state: "Rajasthan",
      type: "Fort",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 5,
      name: "Jaigarh Fort",
      significance:
        "Known for its strong defense mechanism, housing the world's largest cannon on wheels.",
      state: "Rajasthan",
      type: "Fort",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 6,
      name: "Nahargarh Fort",
      significance:
        "Offers panoramic views of Jaipur and was a retreat palace of the royals.",
      state: "Rajasthan",
      type: "Fort",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 1,
      name: "1135 AD",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 5,
      name: "Padao Restaurant",
      banner: "/placeholder.jpg",
    },
  ],
  [
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 7,
      name: "Jal Mahal",
      significance:
        "A stunning palace situated in the middle of Man Sagar Lake.",
      state: "Rajasthan",
      type: "Lake",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 8,
      name: "Man Sagar Lake",
      significance: "A picturesque lake surrounded by hills and the Jal Mahal.",
      state: "Rajasthan",
      type: "Lake",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 9,
      name: "Kanak Vrindavan Garden",
      significance:
        "A beautiful garden with fountains and marble structures near Man Sagar Lake.",
      state: "Rajasthan",
      type: "Scenic",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 8,
      name: "Samode Haveli Restaurant",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 8,
      name: "Suvarna Mahal",
      banner: "/placeholder.jpg",
    },
  ],
  [
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 10,
      name: "Jantar Mantar",
      significance:
        "A UNESCO World Heritage site and one of the largest astronomical observatories.",
      state: "Rajasthan",
      type: "Cultural",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 11,
      name: "City Palace",
      significance:
        "A historic royal palace that showcases a blend of Mughal and Rajput architecture.",
      state: "Rajasthan",
      type: "Cultural",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 12,
      name: "Hawa Mahal",
      significance:
        "Known as the Palace of Winds, it is a five-story pink sandstone structure.",
      state: "Rajasthan",
      type: "Cultural",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 4,
      name: "The Verandah",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 7,
      name: "Peacock Rooftop Restaurant",
      banner: "/placeholder.jpg",
    },
  ],
  [
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 13,
      name: "Ranthambore National Park (entry point at Jaipur)",
      significance: "Famous for its tiger reserve and diverse wildlife.",
      state: "Rajasthan",
      type: "National Park",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 14,
      name: "Jhalana Leopard Safari Park",
      significance:
        "A thriving habitat for leopards and other wildlife within the city limits.",
      state: "Rajasthan",
      type: "National Park",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 15,
      name: "Ram Niwas Garden",
      significance:
        "A historical garden area built by Maharaja Sawai Ram Singh in the 19th century.",
      state: "Rajasthan",
      type: "Nature",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 10,
      name: "Sethi's Restaurant",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 9,
      name: "House of Han",
      banner: "/placeholder.jpg",
    },
  ],
  [
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 16,
      name: "Albert Hall Museum",
      significance:
        "The oldest museum in Rajasthan, showcasing a rich collection of artifacts and arts.",
      state: "Rajasthan",
      type: "Cultural",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 17,
      name: "Central Park",
      significance:
        "A sprawling green space in Jaipur with a musical fountain and walking trails.",
      state: "Rajasthan",
      type: "Nature",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 18,
      name: "Statue Circle",
      significance:
        "A popular landmark in Jaipur built in memory of Maharaja Sawai Jai Singh II.",
      state: "Rajasthan",
      type: "UrbanDevelopment",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 3,
      name: "The Forresta Kitchen & Bar",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 5,
      name: "Tapri Central",
      banner: "/placeholder.jpg",
    },
  ],
  [
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 19,
      name: "Galtaji Temple",
      significance:
        "An ancient Hindu pilgrimage site with natural springs and stunning surroundings.",
      state: "Rajasthan",
      type: "Temple",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 20,
      name: "Sisodia Rani Garden and Palace",
      significance:
        "A charming garden and palace displaying the blend of Mughal and Rajasthani architecture.",
      state: "Rajasthan",
      type: "Scenic",
      banner: "/placeholder.jpg",
    },
    {
      airportWithin50kmRadius: true,
      city: "Jaipur",
      id: 21,
      name: "Abhaneri Stepwell (Chand Baori)",
      significance:
        "A deep four-sided stepwell with intricate carvings, symbolizing the brilliance of ancient architecture.",
      state: "Rajasthan",
      type: "Scenic",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 13,
      name: "RJ14",
      banner: "/placeholder.jpg",
    },
    {
      city: "Jaipur",
      distance: 16,
      name: "Laxmi Misthan Bhandar (LMB)",
      banner: "/placeholder.jpg",
    },
  ],
];
interface ICategory {
  name: string;
  places: string[];
}
export const categoryMapping: ICategory[] = [
  {
    name: "Temples",
    places: [
      "Church",
      "Gurudwara",
      "Mosque",
      "Religious Complex",
      "Religious Shrine",
      "Religious Site",
      "Shrine",
      "Temple",
      "Temples",
      "Spiritual Center",
      "Gurudwara",
      "Shrine",
      "Spiritual Center",
      "Church",
      "Mosque",
      "Temple",
      "Religious Complex",
      "Religious Shrine",
      "Religious Site",
    ],
  },
  {
    name: "Lakes",
    places: ["Lake"],
  },
  {
    name: "Beaches",
    places: ["Beach", "Promenade", "Scenic Area", "River Island"],
  },
  {
    name: "NationalParks",
    places: [
      "National Park",
      "Bird Sanctuary",
      "Wildlife Sanctuary",
      "Botanical Garden",
      "Zoo",
      "Park",
      "Botanical Garden",
    ],
  },
  {
    name: "Forts",
    places: [
      "Fort",
      "Palace",
      "Historical",
      "Monument",
      "War Memorial",
      "Prehistoric Site",
      "Fort",
      "Palace",
      "Memorial",
      "Monument",
      "Mausoleum",
      "Tomb",
      "Tombs",
    ],
  },
  {
    name: "AdventureSports",
    places: ["Adventure Sport", "Ski Resort", "Trekking"],
  },
  {
    name: "Amusement",
    places: [
      "Amusement Park",
      "Theme Park",
      "Film Studio",
      "Entertainment",
      "Race Track",
    ],
  },
  {
    name: "Nature",
    places: [
      "Aquarium",
      "Dam",
      "Cave",
      "Hill",
      "Mountain Peak",
      "Valley",
      "Waterfall",
      "Zoo",
      "Orchard",
      "Tea Plantation",
    ],
  },
  {
    name: "Cultural",
    places: [
      "Cultural",
      "Cricket Ground",
      "Government Building",
      "Museum",
      "Observatory",
      "Rock Carvings",
      "Sculpture Garden",
      "Science",
      "Landmark",
      "Site",
      "Tomb",
      "Tombs",
      "Monastery",
      "Mausoleum",
      "Monument",
      "War Memorial",
    ],
  },
  {
    name: "UrbanDevelopment",
    places: [
      "Commercial Complex",
      "Mall",
      "Market",
      "Township",
      "Urban Development Project",
      "Suspension Bridge",
      "Border Crossing",
    ],
  },
  {
    name: "Scenic",
    places: [
      "Bridge",
      "Confluence",
      "Ghat",
      "Gravity Hill",
      "Island",
      "Landmark",
      "Promenade",
      "Scenic Point",
      "Sunrise Point",
      "Viewpoint",
      "Stepwell",
    ],
  },
];
